network/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("all_posts", views.all_posts, name="all_posts"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("following", views.following, name="following"),
    path("profile/<str:username>", views.profile_view, name="profile"),
    path('follow_unfollow/<str:username>/', views.follow_unfollow, name='follow_unfollow'),
    path("post/<int:post_id>/like", views.like_post, name="like_post"),
    path('image_upload', views.profile_pic_view, name='image_upload'),
    path('edit-bio', views.edit_bio, name='edit-bio'),
    path('success', views.success, name='success'),
    path('search', views.search_user, name="search"),
    
    

    # API Routes
    path("post", views.compose, name="compose"),
    path("posts", views.render_posts, name="posts"),
    path("all-posts", views.render_posts, name="posts"),
    path('post/<int:post_id>/edit', views.edit, name="edit"),
    path("following-posts", views.following_posts, name="following_posts"),
    path("profile-list/<str:username>", views.follow_list, name="follow_list"),
    path("profile-posts/<str:username>", views.profile_posts, name="profile-posts"),
    path("post/<int:post_id>/liked_by_current_user", views.liked_by_current_user, name="liked_by_current_user"),
    path('suggestions', views.user_suggestion, name="suggestions"),
    
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    
    bio = models.TextField(null=True)
    birthdate = models.DateField(null=True, blank=True)
    location = models.TextField(blank=True)
    profileimg = models.ImageField(upload_to='profile_images', default='blank-profile-picture.png')
    following = models.ManyToManyField('self', through='Relationship', symmetrical=False, related_name='followers')

    def __str__(self):
        return self.username
    
    def who_I_follow(self):
        return [user.username for user in self.following.all()]
    
    def my_followers(self):
        return [relationship.user.username for relationship in self.follows.all()]
    
    

class Post(models.Model):
    author = models.ForeignKey("User", on_delete=models.CASCADE, related_name="author")
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, blank = True, null = True)
    def total_likes(self):
        return self.likes.count()
    def serialize(self, user=None):
        serialized_data = {
            "author": {
                "id": self.author.id,
                "username": self.author.username,
                "profileimg": self.author.profileimg.url
            },
            "is_author": self.author.username == user.username,
            "content": self.content,
            "date_posted": self.date_posted.strftime("%b %d %Y, %I:%M %p"),
            "likes": [user.id for user in self.likes.all()],
            "total_likes": self.total_likes() ,
            "id": self.id,
        }
        if user is not None:
            serialized_data["user_has_liked"] = user in self.likes.all()
        return serialized_data
    

class Relationship(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    follows = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follows')

class Comment(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

network/views.py
import json
import random
import time

from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect
from django import forms
from django.contrib import messages


from .models import User, Post

class ProfileForms(forms.ModelForm):
    profileimg = forms.ImageField(label="Profile Picture")

    class Meta:
        model = User
        fields = ('profileimg',)

class BioForms(forms.ModelForm):
    bio = forms.CharField(label="Bio")

    class Meta:
        model = User
        fields = ('bio',)

def user_suggestion(request):
    
    user_info = [(user.username, user.profileimg) for user in User.objects.all()]
    
    user_info = [{'username': user.username, 'profileimg': '/media/' + str(user.profileimg)} for user in User.objects.all() if user != request.user]
    random.shuffle(user_info)   
    if user_info:
        return JsonResponse(user_info, safe=False)

    else:
        return JsonResponse({"suggestions": 'No one to know'}, status=201)
            
       


def search_user(request):
    if request.method == "GET":
        q = request.GET.get('q', '')
        usernames = [user.username for user in User.objects.all()]        
        lowercase_results = [item.lower() for item in usernames]
        lowercase_dict = {item.lower(): item for item in usernames}
        sub_strings = [lowercase_dict[item] for item in lowercase_results if q.lower() in item]

        if sub_strings:
            return render(request, "network/search.html", {"entries": sub_strings})
        else:
            return render(request, "network/search.html", {"message": f"No user with {q} in it's name found."})
    else:
        return render(request, "network/search.html", {"message": "Method is not GET!"})
    
def edit_bio(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            current_user = request.user
            bio_form = BioForms(request.POST, instance=current_user)
            if bio_form.is_valid():
                bio_form.save()
                return redirect('profile', username=current_user.username)
        else:
            form = BioForms()
        return render(request, 'profile.html', {'form': form})
    else:
        return redirect('login')
        

def profile_pic_view(request):
    
    if request.user.is_authenticated:
        print(request.user.is_authenticated)
        if request.method == 'POST':
            current_user = request.user
            form = ProfileForms(request.POST or None, request.FILES or None, instance=current_user)
            
            if form.is_valid():
                
                form.save()
            
                
                return redirect('profile', username=current_user.username)
        else:
            form = ProfileForms()

        return render(request, 'profile.html', {'form': form})
    else:
        return redirect('login')


def success(request):
    return HttpResponse('successfully uploaded')

@csrf_exempt
def index(request):
    if request.user.is_authenticated:
        return redirect('all_posts')
    else:
        return render(request, "network/index.html")

def all_posts(request):
    return render(request, "network/all_posts.html")

@csrf_exempt
@login_required
def edit(request, post_id):
    try:
        post = Post.objects.get(author=request.user, pk=post_id)
    except Post.DoesNotExist:
        return JsonResponse({"error": "Post not found."}, status=404)
    
    if request.method == "PUT":
        data = json.loads(request.body)
        post.content = data["body"]
        post.save()
        return HttpResponse(status=204)
    else:
        return JsonResponse({
            "error": "PUT request required."
        }, status=400)


@csrf_exempt
@login_required
def compose(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        content = data['content']
        author = request.user
        post = Post(
            author = author,
            content = content

        )
        post.save()
        print(content)
        return JsonResponse({"message": "Post successfully published"}, status=201)

        # process the content
    return JsonResponse({"error": "POST request required."}, status=400)
    
def render_posts(request):
    
    start = int(request.GET.get("start") or 0)
    end = int(request.GET.get("end") or (start + 9))
    
    base_query = Post.objects
    posts = base_query.order_by("-date_posted")[start:end+1]
    time.sleep(1)
    return JsonResponse([post.serialize(request.user) for post in posts], safe=False)

def follow_unfollow(request, username):
    if request.method == 'POST':
        
        other_user = User.objects.get(username=username)
        if request.user.following.filter(username=username).exists():
            request.user.following.remove(other_user)

        else:
            request.user.following.add(other_user)
        return redirect('profile', username=username)
    return redirect('profile', username=username)

def liked_by_current_user(request, post_id):
    
    post = Post.objects.get(id=post_id)

    
    liked = request.user.id in post.likes.values_list('id', flat=True)
   
    
    return JsonResponse({'liked': liked})


@csrf_exempt
def like_post(request, post_id):
    if request.method == "POST":
        try:
            post = Post.objects.get(id=post_id)
        except Post.DoesNotExist:
            return JsonResponse({'error': 'Post not found'}, status=404)

        if request.user in post.likes.all():
            post.likes.remove(request.user)
            action = 'unliked'
        else:
            post.likes.add(request.user)
            action = 'liked'
        post.save()
        return JsonResponse({'success': True,
                             'action': action})
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

def profile_posts(request, username):
    user = User.objects.get(username=username)
    base_query = Post.objects.filter(author=user)
    posts = base_query.order_by("-date_posted").all()
    
    return JsonResponse([post.serialize (request.user) for post in posts], safe=False)

from django.http import Http404

def profile_view(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        raise Http404("User does not exist")

    if request.user.is_authenticated:
        following_count = user.followers.count()
        followers_count = user.following.count()
        posts_count = Post.objects.filter(author=user).count()
        bio = user.bio
        form = ProfileForms(instance=request.user)
        profile_img = user.profileimg
        
        is_following = request.user.following.filter(username=username).exists()
        
        return render(request, "network/profile.html", 
                      {'name':username, 
                       'posts_count': posts_count,
                       'profile_img': profile_img,
                       'bio': bio,
                       'following_count': following_count, 
                       'followers_count': followers_count, 
                       'is_following': is_following,
                       'form': form
                       })
    else:
        return redirect('login')


def follow_list(request, username):
    user = User.objects.get(username=username)
    followers_usernames = user.my_followers()
    following_usernames = user.who_I_follow()  
    return JsonResponse({
        'followers': followers_usernames,
        'following': following_usernames
    })



def following(request):
    return render(request, "network/following.html")

def following_posts(request):
    
    user = User.objects.get(username=request.user.username)
    following = user.following.all()
    
    base_query = Post.objects.filter(author__in=following)
    posts = base_query.order_by("-date_posted").all()
    return JsonResponse([post.serialize (request.user) for post in posts], safe=False)
    

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")

network/templates/network/all_posts.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}

    {% if message %}
        <div style='text-align:center;'>{{ message }}</div>
    {% endif %}

    <div style='text-align:center;'>
            
        <h1>
            <b>
                <strong>
                    For You
                </strong>
            </b>
        </h1>
    </div>

    {% if user.is_authenticated %}

    <script type="text/babel" src="{% static 'network/react.jsx' %}"></script>
        <div id="react-root"></div>
    {% endif %}


    <div id="posts-view">
    </div>
   

    {% block script %}
        <script src="{% static 'network/post.js' %}"></script>
        <script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
        <script>
            var MEDIA_URL = "{{ MEDIA_URL }}";
        </script>
    {% endblock %}
{% endblock %}

network/templates/network/following.html
{% extends "network/layout.html" %}
{% load static %}
{% block body %}

    {% if user.is_authenticated %}
        <div style='text-align:center;'>
            
            <h1>
                <b>
                    <strong>
                        
                        People you follow
                    </strong>
                </b>
            </h1>
        </div>
        <div id="posts-view">
        </div>
        {% block script %}
            <script src="{% static 'network/post.js' %}"></script>
        {% endblock %}
    {% endif %}
{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <div class="Tinger">   
        <h1>
            <b>
                <strong>
                    <i class="fa-solid fa-hashtag"></i>
                    Tinger
                </strong>
            </b>
        </h1>
    </div>
    <div class="info">
        <h3>
            <p>
                Connect with friends and the world around you on Tinger
            </p>
            <a id= "ind" href="{% url 'login' %}"> Log in </a>
                 to start Tingering around the world <i class="fa-solid fa-globe"></i>
            <br>
            <br>
                New Here? You can 
                <a id= "ind" href="{% url 'register' %}"> Register </a>
                 for Free
            
        </h3>
    </div>
   {% block script %}
   <script src="{% static 'network/post.js' %}"></script>
        <script>
            var MEDIA_URL = "{{ MEDIA_URL }}";
        </script>
        {% endblock %}
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Tinger{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'network/styles.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://kit.fontawesome.com/99cd413302.js" crossorigin="anonymous"></script>
        
        
    </head>
    <body>
        <div class="left-bar">
            <nav>
                <a class="navbar-brand" href="{% url 'index' %}">
                    <h1>
                        <b>
                            <strong>
                                <i class="fa-solid fa-hashtag"></i>
                                Tinger
                            </strong>
                        </b>
                    </h1>
                </a>
            
                <div>
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a id="username-link" class="nav-link" href="/profile/{{user.username}}">
                                <strong>
                                    <i class="fa-solid fa-user"></i>
                                    {{ user.username }}
                                    
                                </strong></a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a id="all-posts" class="nav-link" href="{% url 'all_posts' %}">
                            <i class="fa-solid fa-globe"></i>
                            All Posts
                            
                        </a>
                    </li>
                    
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form action="{% url 'search' %}" method="get" style="display: flex; align-items: center; ">
                            <i class="fa-solid fa-magnifying-glass" style="color: #ffffff;"></i>
                            <input class="search" type="text" name="q" placeholder="Search User" style="margin-left: 5px; flex: 1; width: 250px;">
                        </form>       
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'following' %}">
                                <i class="fa-solid fa-person-walking"></i>
                                Following
                                
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">
                                <i class="fa-solid fa-right-from-bracket"></i>
                                Log Out
                                
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">
                                <i class="fa-solid fa-right-to-bracket"></i>
                                Log In
                                
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">
                                <i class="fa-solid fa-id-card"></i>
                                Register
                                
                            </a>
                        </li>
                    {% endif %}
                </ul>
                </div>
            </nav>
        </div>
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
        <div class="right-bar">
            <i class="fa-solid fa-user-plus"></i>
            You might know them
            <hr>
            <div class="user-suggestions">
                {% for suggestion in suggestions %}
                <div>
                    <a id="ind" href="/profile/{{suggestion}}">{{ suggestion }} </a>
                </div>
                
                {% endfor %}
            </div>
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <div class="form">
        <div class="login-form">
            
            <h5>
                <b>
                    <strong>
                        Login
                    </strong>
                </b>
            </h5>
            <hr>
            {% if message %}
                <div>{{ message }}</div>
            {% endif %}

            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
                <input class="btn btn-primary" type="submit" value="Login">
            </form>
            <hr>
            Don't have an account? <a id= "ind" href="{% url 'register' %}">Register here.</a>
        </div>
    </div>
{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}


    <div class="profile-section">
        <div class="puopff">
            <div class="puo">
                <div class="profile-pic">
                    <img src="{{ profile_img.url }}" alt="Profile Picture" width="100" class="prof-pic">             
                </div>
                <div class="username">
                    <strong>{{ name }}</strong>
                </div>
                <div class="option">
                    {% if user.is_authenticated %}
                        {% if user.username != name %} 
                            <form method="POST" action="{% url 'follow_unfollow' name %}">
                                {% csrf_token %}
                                <input type="submit" value="{% if is_following %}Unfollow{% else %}Follow{% endif %}">
                            </form>
                        {% else %}
                            <button id="settings">
                                Edit Profile
                                <i class="fas fa-cog"></i>
                            </button>
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <div class="bio"> 
                <div><b>Bio: </b> 
                {{ bio }}
                </div>
                {% if user.is_authenticated %}
                        {% if user.username == name %} 
                            <button id="edit-bio-btn">
                                Edit Bio
                                <i class="fas fa-cog"></i>
                            </button>
                        {% endif %}
                {% endif %}
            </div>
            
                
                            <form action="/edit-bio" method="post" class="edit-bio">
                                {% csrf_token %}
                                
                                    <p>
                                        <label for="id_profilebio"><b>Bio: </b> </label>
                                        <input type="text" name="bio" id="id_profilebio" value="{{ bio }}" required>
                                    </p>
                                
                                <button type="submit" id="edit-bio-btn">
                                    Save Bio 
                                    <i class="far fa-save"></i>
                                </button>
                            </form>
                
            

            <div class="pff">  
                <div id="nr-posts">
                    <b>
                    <div> {{ posts_count }}</div>
                    Posts
                    </b>
                </div>
                <button id="followers">
                    <b>
                    <div> {{ following_count }}</div>
                    Followers
                    </b>
                </button>
                <button id="followings">
                    <b>
                    <div>{{ followers_count }}</div> 
                    Following
                    </b>
                </button>
                        
            </div>
            <div class="profile-edit">
                <form method="POST" enctype="multipart/form-data" action="{% url 'image_upload' %}">
                    {% csrf_token %}
                    <p>
                        <label for="id_profileimg">Profile Picture:</label>
                        <input type="file" name="profileimg" id="id_profileimg" required>
                    </p>
                    <button type="submit">Upload</button>
                </form>
            </div>
        </div>

        

        <div class="modal" id="modal">
            <div class="modal-inner">
                <h2 id="modal-title">Followers</h2>
                    <div id="followers-container">
                        
                    </div>
                <button id="closeModal">
                    Close
                </button>
            </div>
        </div>
    </div>

    <div id="app"></div>

    <div id="posts-view">
    </div>
    {% block script %}
        <script src="{% static 'network/post.js' %}"></script>
        <script src="{% static 'network/profile.js' %}"></script>
        
    {% endblock %}

{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

<div class="form">
    <div class="register-form">

        <h5>
            <b>
                <strong>
                    Register
                </strong>
            </b>
        </h5>
        <hr>
        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Register">
        </form>
        <hr>
        Already have an account? <a id= "ind" href="{% url 'login' %}">Log In here.</a>
    </div>
</div>
{% endblock %}

network/templates/network/search.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}



{% if user.is_authenticated %}
{% endif %}
    <div style='text-align:center;'>        
        <h1>
            <b>
                <strong>
                    
                    Search Results
                </strong>
            </b>
        </h1>
    </div>

    {% if message %}
        <div style='text-align:center;'> {{ message }}</div>
    {% endif %}
    
    {% for entry in entries %}
        <div style='text-align:center;'><a id="ind" href="/profile/{{entry}}">{{ entry }} </a></div>
            
        {% endfor %}
   
{% block script %}

{% endblock %}
{% endblock %}